version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: web-server.dockerfile
    ports:
      - "11000:11000"

  frontend:
    build:
      context: .
      dockerfile: web-client.dockerfile
    ports:
      - "11001:11001"
    depends_on:
      - backend
